#baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Exported"
theme = "nuo"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License."
PygmentsCodeFences = true

[params]
author = "Xavier Stevens"
github = "xstevens"
twitter = "xstevens"
avatar = "images/avatar.png"
paginate = 10
